name: CI
run-name: CI - ${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - 'trunk'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Loading java and cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build
