name: Publish package to the Maven Central Repository
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Loading java and cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "central",
              "username": "${{ secrets.OSSRH_USERNAME }}",
              "password": "${{ secrets.OSSRH_TOKEN }}"
            },{
              "id": "sign-key-id",
              "passphrase": "${{ secrets.GPG_SIGNING_PASSPHRASE }}",
              "privateKey": "${{ secrets.GPG_SIGNING_KEY }}"        
            }]
      - name: Set project version
        run: ./mvnw versions:set -DnewVersion=${{ github.event.release.tag_name }}
      - name: Publish package
        run: ./mvnw deploy
